Use my_stpcpy instead of strmov
```
/data/making/q4m/mysql-5.7.24/storage/q4m/src/ha_queue.cc:693:39: error: ‘please_use_my_stpcpy_or_my_stpmov_rather_than_strmov’ was not declared in this scope
   strmov(share->table_name, table_name);
                                       ^
```

ref: Bug#17429539: STRMOV() CAN BE DEFINED TO STPCPY()
mysql/mysql-server@1f8d59acbc9f62e2aa93b5f475bca8de99be4d05