Use q4m_my_free instead of my_free to fix compile error
```
/data/making/q4m/mysql-5.7.24/storage/q4m/src/ha_queue.cc:62:39: error: ‘my_free’ was not declared in this scope
 #define my_free(PTR, FLAG) my_free(PTR)
                                       ^
```